### ISSUE TITLE
Chat Support

### ISSUE THREAD

**Issue by udfalkso** [mgallo/openai.ex#14]
### Describe the feature or improvement you're requesting

This just dropped:
https://platform.openai.com/docs/guides/chat

Would be wonderful to get support in your library for it.  If you don't have time in the near future I will try add it myself.  Thx!

**Comment by fruizg0302** [comment]
Thank you mate!

**Comment by fruizg0302** [comment]
Again, thanks for your hard work @mgallo you rock

**Comment by mgallo** [comment]
👋 added support to chat completions in `v0.3.1`

hex link: https://hex.pm/packages/openai/0.3.1
documentation: https://github.com/mgallo/openai.ex#chat_completion

**known issue:** There is an issue with the `stream` param (false by default), because my current client implementation doesn't support SSE properly. I think I'll address it together with the changes for #13 in the refactoring of the client.

#### Example request
```elixir
OpenAI.chat_completion(
  model: "gpt-3.5-turbo",
  messages: [
        %{role: "system", content: "You are a helpful assistant."},
        %{role: "user", content: "Who won the world series in 2020?"},
        %{role: "assistant", content: "The Los Angeles Dodgers won the World Series in 2020."},
        %{role: "user", content: "Where was it played?"}
    ]
)
```

#### Example response
```elixir
{:ok,
     %{
       choices: [
         %{
           "finish_reason" => "stop",
           "index" => 0,
           "message" => %{
             "content" =>
               "The 2020 World Series was played at Globe Life Field in Arlington, Texas due to the COVID-19 pandemic.",
             "role" => "assistant"
           }
         }
       ],
       created: 1_677_773_799,
       id: "chatcmpl-6pftfA4NO9pOQIdxao6Z4McDlx90l",
       model: "gpt-3.5-turbo-0301",
       object: "chat.completion",
       usage: %{
         "completion_tokens" => 26,
         "prompt_tokens" => 56,
         "total_tokens" => 82
       }
     }}
```

**Comment by udfalkso** [comment]
Amazing, thx!
